//
//  LaunchScreenProtocols.swift
//  Maxi Taxi
//
//  Created Gerardo Jacobo Luna on 21/11/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol LaunchScreenWireframeProtocol: class {
    func goToMap()

}
//MARK: Presenter -
protocol LaunchScreenPresenterProtocol: class {
    func goToMap()

}

//MARK: Interactor -
protocol LaunchScreenInteractorProtocol: class {

  var presenter: LaunchScreenPresenterProtocol?  { get set }
}

//MARK: View -
protocol LaunchScreenViewProtocol: class {

  var presenter: LaunchScreenPresenterProtocol?  { get set }
}
