//
//  LaunchScreenViewController.swift
//  Maxi Taxi
//
//  Created Gerardo Jacobo Luna on 21/11/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LaunchScreenViewController: UIViewController, LaunchScreenViewProtocol {

	var presenter: LaunchScreenPresenterProtocol?

    @IBOutlet weak var iconLauncher: UIImageView!
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        UIView.animate(withDuration: 2, delay: 0, options: .curveEaseInOut, animations: {
            self.iconLauncher.transform = CGAffineTransform(scaleX: 0.6, y: 0.6)
        }, completion: { _ in
            //self.presenter?.goToMap()
            self.presenter?.goToLogin()
        })
    }
}
