//
//  LaunchScreenInteractor.swift
//  Maxi Taxi
//
//  Created Gerardo Jacobo Luna on 21/11/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LaunchScreenInteractor: LaunchScreenInteractorProtocol {

    weak var presenter: LaunchScreenPresenterProtocol?
}
