//
//  LaunchScreenPresenter.swift
//  Maxi Taxi
//
//  Created Gerardo Jacobo Luna on 21/11/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LaunchScreenPresenter: LaunchScreenPresenterProtocol {

    weak private var view: LaunchScreenViewProtocol?
    var interactor: LaunchScreenInteractorProtocol?
    private let router: LaunchScreenWireframeProtocol

    init(interface: LaunchScreenViewProtocol, interactor: LaunchScreenInteractorProtocol?, router: LaunchScreenWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    func goToMap(){
        router.goToMap()
    }
    func goToLogin(){
        router.goToLogin()
    }
}
