//
//  LaunchScreenRouter.swift
//  Maxi Taxi
//
//  Created Gerardo Jacobo Luna on 21/11/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import GoogleMaps

class LaunchScreenRouter: LaunchScreenWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = LaunchScreenViewController(nibName: nil, bundle: nil)
        let interactor = LaunchScreenInteractor()
        let router = LaunchScreenRouter()
        let presenter = LaunchScreenPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    func goToMap(){
        let mapView = GoogleMapRouter.createModule()
        GMSServices.provideAPIKey("")
        let navigationController = UINavigationController(rootViewController: mapView)
        UIApplication.shared.windows.first?.rootViewController = navigationController
    }
    func goToLogin(){
        let loginView = LoginScreenRouter.createModule()
        let navigationController = UINavigationController(rootViewController: loginView)
        UIApplication.shared.windows.first?.rootViewController = navigationController
    }
}
