//
//  LoginScreenProtocols.swift
//  Maxi Taxi
//
//  Created Gerardo Jacobo Luna on 30/01/25.
//  Copyright © 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol LoginScreenWireframeProtocol: class {
    func navigateHome()

}
//MARK: Presenter -
protocol LoginScreenPresenterProtocol: class {
    func navigateHome()
    func loginSucces()
    func loginError(message:String)
    func login(name:String, pass:String)

}

//MARK: Interactor -
protocol LoginScreenInteractorProtocol: class {

  var presenter: LoginScreenPresenterProtocol?  { get set }
    func login(name:String, pass:String)
}

//MARK: View -
protocol LoginScreenViewProtocol: class {

  var presenter: LoginScreenPresenterProtocol?  { get set }
    func loginSucces()
    func loginError(message:String)
}
