//
//  LoginScreenProtocols.swift
//  Maxi Taxi
//
//  Created Gerardo Jacobo Luna on 30/01/25.
//  Copyright © 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol LoginScreenWireframeProtocol: class {

}
//MARK: Presenter -
protocol LoginScreenPresenterProtocol: class {

}

//MARK: Interactor -
protocol LoginScreenInteractorProtocol: class {

  var presenter: LoginScreenPresenterProtocol?  { get set }
}

//MARK: View -
protocol LoginScreenViewProtocol: class {

  var presenter: LoginScreenPresenterProtocol?  { get set }
}
