//
//  LoginScreenPresenter.swift
//  Maxi Taxi
//
//  Created Gerardo Jacobo Luna on 30/01/25.
//  Copyright © 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginScreenPresenter: LoginScreenPresenterProtocol {

    weak private var view: LoginScreenViewProtocol?
    var interactor: LoginScreenInteractorProtocol?
    private let router: LoginScreenWireframeProtocol

    init(interface: LoginScreenViewProtocol, interactor: LoginScreenInteractorProtocol?, router: LoginScreenWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    func login(name: String, pass: String){
        interactor?.login(name: name, pass: pass)
    }
    func loginError(message: String) {
        view?.loginError(message: message)
    }
    func loginSucces() {
        view?.loginSucces()
    }
    func navigateHome(){
        router.navigateHome()
    }
}
