//
//  GoogleMapViewController.swift
//  Maxi Taxi
//
//  Created Gerardo Jacobo Luna on 21/11/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import GoogleMaps
import CoreLocation

class GoogleMapViewController: UIViewController, GoogleMapViewProtocol, CLLocationManagerDelegate {

	var presenter: GoogleMapPresenterProtocol?
    
    var mapView: GMSMapView!
    let locationManager = CLLocationManager()

	override func viewDidLoad() {
        super.viewDidLoad()
        
        // Configura el administrador de ubicación
        locationManager.delegate = self
        locationManager.requestWhenInUseAuthorization()
        locationManager.startUpdatingLocation()
        
        // Configura el mapa de Google
        let camera = GMSCameraPosition.camera(withLatitude: 0, longitude: 0, zoom: 15.0)
        mapView = GMSMapView.map(withFrame: self.view.bounds, camera: camera)
        mapView.isMyLocationEnabled = true // Muestra el punto azul de ubicación del usuario
        self.view.addSubview(mapView)
        
        // Configura la cámara inicial del mapa
        mapView.settings.myLocationButton = false
        mapView.settings.compassButton = true
        mapView.settings.indoorPicker = false
        mapView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        
        view.addSubview(mapView)
        view.sendSubviewToBack(mapView)
        mapView.isHidden = false
        
    }
    // Actualiza la cámara del mapa con la ubicación del usuario
    func locationManager(_ manager: CLLocationManager, didUpdateLocations locations: [CLLocation]) {
        if let location = locations.last {
            let camera = GMSCameraPosition.camera(withLatitude: location.coordinate.latitude, longitude: location.coordinate.longitude, zoom: 15.0)
            mapView.animate(to: camera)
            print("Ubicación del usuario: Latitud \(location.coordinate.latitude), Longitud \(location.coordinate.longitude)")
        }
    }
    // Manejo de errores
    func locationManager(_ manager: CLLocationManager, didFailWithError error: Error) {
        print("Error al obtener la ubicación: \(error.localizedDescription)")
    }
}
