//
//  GoogleMapRouter.swift
//  Maxi Taxi
//
//  Created Gerardo Jacobo Luna on 21/11/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GoogleMapRouter: GoogleMapWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = GoogleMapViewController(nibName: nil, bundle: nil)
        let interactor = GoogleMapInteractor()
        let router = GoogleMapRouter()
        let presenter = GoogleMapPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
