//
//  GoogleMapPresenter.swift
//  Maxi Taxi
//
//  Created Gerardo Jacobo Luna on 21/11/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GoogleMapPresenter: GoogleMapPresenterProtocol {

    weak private var view: GoogleMapViewProtocol?
    var interactor: GoogleMapInteractorProtocol?
    private let router: GoogleMapWireframeProtocol

    init(interface: GoogleMapViewProtocol, interactor: GoogleMapInteractorProtocol?, router: GoogleMapWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
