//
//  GoogleMapViewController.swift
//  Maxi Taxi
//
//  Created Gerardo Jacobo Luna on 21/11/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import GoogleMaps

class GoogleMapViewController: UIViewController, GoogleMapViewProtocol {

	var presenter: GoogleMapPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        // Configura la cámara inicial del mapa
        let camera = GMSCameraPosition.camera(withLatitude: 20.124235315384155, longitude: -98.73545304924497, zoom: 15.0)
        let mapView = GMSMapView.map(withFrame: self.view.bounds, camera: camera)
        mapView.settings.myLocationButton = false
        mapView.settings.compassButton = true
        mapView.settings.indoorPicker = false
        mapView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        
        view.addSubview(mapView)
        view.sendSubviewToBack(mapView)
        mapView.isHidden = false
        
        
        // Opcional: Añade un marcador al mapa
        let marker = GMSMarker()
        marker.position = CLLocationCoordinate2D(latitude: 20.124235315384155, longitude: -98.73545304924497)
        marker.title = "Pachuca Centro"
        marker.snippet = "Hidalgo"
        marker.map = mapView
        marker.icon = UIImage(named: "UbicacionUser")
        
    }
}

