//
//  GoogleMapProtocols.swift
//  Maxi Taxi
//
//  Created Gerardo Jacobo Luna on 21/11/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol GoogleMapWireframeProtocol: class {

}
//MARK: Presenter -
protocol GoogleMapPresenterProtocol: class {

}

//MARK: Interactor -
protocol GoogleMapInteractorProtocol: class {

  var presenter: GoogleMapPresenterProtocol?  { get set }
}

//MARK: View -
protocol GoogleMapViewProtocol: class {

  var presenter: GoogleMapPresenterProtocol?  { get set }
}
